title: "Mastraで作るAIエージェント入門――GitHub解析で学ぶ自動化の第一歩"
summary: "MastraというAIエージェント開発フレームワークを使って、GitHubリポジトリを解析するエージェントを開発する方法を解説します。初心者でも理解できるように基本から応用まで丁寧に説明し、実践的なプロジェクトを通じてAIエージェント開発のスキルを身につけることができます。"
topics: ["AI", "エージェント", "Mastra", "GitHub", "自動化"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
    - introduction
    - getting-started
    - workshop
    - agents
    - workflows
    - rag
    - local-dev
    - deployment
    - evals
    - conclusion
